### ISSUE TITLE
Missing author information from Scienti

### ISSUE THREAD

**Issue by restrepo** [colav-playground/advanced_user_tests#5]
The work:

* `_id:"641ba3a21654767daee85bcb"`
* and `external_ids`:
   * `doi: "10.1103/physrevd.101.035004"`
   * `COD_RH:"0000707619"`
   * `COD_PRODUCTO:"52"`
   
[Has only one registered author in Scienti](http://apis.colav.co/scienti/product?apikey=*****&model_year=2022&institution=udea&COD_RH=0000707619&COD_PRODUCTO=52)  (change `apikey`)

In the work, the author Julian Calle only has the OpenAlex information.

However, an article _with the same doi_ [also appears in Scienti](http://apis.colav.co/scienti/product?apikey=*****&model_year=2022&institution=udea&COD_RH=0000177733&COD_PRODUCTO=138)  (change `apikey`) with:

   * `COD_RH:"0000177733"`
   * `COD_PRODUCTO:"138"`
 
with all the three authors and the corresponding Scienti information for Julian Calle. The information for such one author would be taken from this second record.

**Important**: This two extra Scienti primary keys would be added to the list of `external_ids`:
```python
[{'source': 'openalex', 'id': 'https://openalex.org/W2974772295'},
 {'source': 'doi', 'id': '10.1103/physrevd.101.035004'},
 {'source': 'mag', 'id': '2974772295'},
 {'source': 'wos', 'id': '000511446300002'},
 {'source': 'COD_RH', 'id': '0000707619'},
 {'source': 'COD_PRODUCTO', 'id': '52'},
 {'source': 'scholar', 'id': '0UBo6ZcLtU4J'},
 {'source': 'scopus', 'id': '2-s2.0-85079782989'},
 {'source': 'COD_RH', 'id': '0000177733'},
 {'source': 'COD_PRODUCTO', 'id': '138'}]
```
The first one is the one that has registered the research group

**Comment by muzgash** [comment]
The suggested paper to include the information of another author with ids:
COD_RH:"0000177733"
COD_PRODUCTO:"138"
does not exists in the agreed database.
