### ISSUE TITLE
Remove sensible information from `data=person` API response

### ISSUE THREAD

**Issue by restrepo** [colav-playground/advanced_user_tests#8]
Remove fields: marital_status, birthplace,birthdate

http://clustercien.udea.edu.co:8080/api/search?data=person&keywords=Diego+Alejandro+Restrepo+Quintero

**Comment by muzgash** [comment]
Fixed!

http://clustercien.udea.edu.co:8080/api/search?data=person&keywords=Diego+Alejandro+Restrepo+Quintero
